# Generated by Django 5.1.4 on 2024-12-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_local_entrylocal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryLocal',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
